### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by itanivalkyrie** [reinhartP/Twitter-Likes-Media-Downloader#3]
```
Traceback (most recent call last):
  File "twitter_likes.py", line 104, in <module>
    downloader.main()
  File "twitter_likes.py", line 96, in main
    self.downloadLikes(api, args.user, args.force)
  File "twitter_likes.py", line 14, in downloadLikes
    liked_tweets = Likes(api, screen_name, self._current_path, force_redownload)
  File "/home/installation/twitter-likes-media-downloader/twitter-likes-media-downloader/likes.py", line 21, in __init__
    conn = sqlite3.connect(os.path.join(os.path.normpath(
sqlite3.OperationalError: unable to open database file
```
Is there a way to solve this issue ? Try to modify in likes.py line 22 without success. 

Thanks for your help or advice. 

![image](https://user-images.githubusercontent.com/2438572/172215636-14e40e85-6bd3-4100-af22-3ae5ce0ee3d2.png)

**Comment by reinhartP** [comment]
Try it out now. It should create the database file in the same folder

**Comment by itanivalkyrie** [comment]
Work as expected 👍 
Thanks for your work.
